name: Deploy to GitHub Pages if Files Changed

on:
  push:
    branches:
      - main  # Trigger this workflow on pushes to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check for file changes
        id: changes
        run: |
          git fetch origin gh-pages || echo "No gh-pages branch yet"
          
          # Check if gh-pages branch exists
          if git show-ref --quiet refs/remotes/origin/gh-pages; then
            echo "gh-pages branch exists. Checking for changes..."
            git diff --name-only origin/gh-pages..HEAD > changed_files.txt
          else
            echo "First deployment, treating all files as changed"
            find . -type f > changed_files.txt  # Consider all files as changed
          fi
          
          COUNT=$(wc -l < changed_files.txt)
          echo "Changed files count: $COUNT"
          echo "changed=$COUNT" >> $GITHUB_ENV

      - name: Cancel if no changes
        if: env.changed == '0'
        run: |
          echo "No changes detected. Skipping deployment."
          exit 0

      - name: Deploy to GitHub Pages
        if: env.changed != '0'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Change to ./dist or ./build if you're using a build step
